import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });
import "./../globals.css"

export const metadata: Metadata = {
  title: "Implement Auth",
  description: "Generated by create next app",
};


export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Toaster richColors />
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
